### ISSUE TITLE
Eternal loading on startup

### ISSUE THREAD

**Issue by clawzxb** [cocktailpeanut/xtts.pinokio#1]
![image](https://github.com/cocktailpeanut/xtts.pinokio/assets/75501418/bcb3a4f8-23c0-4d09-8a5c-1c5d45197fe2)

what is causing this problem? everything is set up, but it hangs forever at this moment

**Comment by chibanem** [comment]
Im having the same issue , is there a solution ?

**Comment by jackburton75** [comment]
same problem

(env) D:\Pinokio\api\xtts.pinokio.git>python app.py
 > tts_models/multilingual/multi-dataset/xtts_v1 is already downloaded.
Traceback (most recent call last):
  File "D:\Pinokio\api\xtts.pinokio.git\app.py", line 13, in <module>
    tts = TTS("tts_models/multilingual/multi-dataset/xtts_v1")
  File "D:\Pinokio\api\xtts.pinokio.git\env\lib\site-packages\TTS\api.py", line 81, in __init__
    self.load_tts_model_by_name(model_name, gpu)
  File "D:\Pinokio\api\xtts.pinokio.git\env\lib\site-packages\TTS\api.py", line 185, in load_tts_model_by_name
    self.synthesizer = Synthesizer(
  File "D:\Pinokio\api\xtts.pinokio.git\env\lib\site-packages\TTS\utils\synthesizer.py", line 109, in __init__
    self._load_tts_from_dir(model_dir, use_cuda)
  File "D:\Pinokio\api\xtts.pinokio.git\env\lib\site-packages\TTS\utils\synthesizer.py", line 161, in _load_tts_from_dir  
    config = load_config(os.path.join(model_dir, "config.json"))
  File "D:\Pinokio\api\xtts.pinokio.git\env\lib\site-packages\TTS\config\__init__.py", line 95, in load_config
    data = read_json_with_comments(config_path)
  File "D:\Pinokio\api\xtts.pinokio.git\env\lib\site-packages\TTS\config\__init__.py", line 22, in read_json_with_comments
    data = json.loads(input_str)
  File "D:\Pinokio\bin\python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Pinokio\bin\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Pinokio\bin\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

(env) D:\Pinokio\api\xtts.pinokio.git>

nothing !

**Comment by geissgold** [comment]
Still happening 👆🏼 same error from the JSONDecodeError. Will probably uninstall for now and check in later.

**Comment by fancellu** [comment]
> raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


Same for me

**Comment by rudak** [comment]
same for me :( 
![image](https://github.com/cocktailpeanut/xtts.pinokio/assets/604478/b26a71be-7a3c-4311-a9c9-624a30286c26)

**Comment by matasoy** [comment]
How can we install TTS module ?
No one answered this...

**Comment by ApacheBlack** [comment]
same here using Pinokio! someone on the internet seems to have the solution and its downgrading to Python 9 ot 10. am not willing to do that.
